project:
  type: website

website:
  title: "Lochana Perera"
  navbar:
    background: "#f5f5f7"

format:
  html:
    theme: default
    toc : true
    toc-depth : 2
    toc-title: "On this page"

    backgroundcolor: "#f5f5f7"
    
    include-in-header:
      text: |
        <style>
         /* 1. Base State - Using your exact values */
          main img, .cell-output-display img {
            border-radius: 16px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);
            transition: transform 0.3s cubic-bezier(0.25, 0.8, 0.25, 1), box-shadow 0.3s ease;
            
            /* Optional: Adds a white background so transparent plots look solid */
            background-color: white; 
          }
        </style>  